export class motorcycles{
    imgSrc:string=''
    name:string=''
    price:string=''
    power:string=''
    performance:string=''
    fuelTankCapacity:string=''
    engineCapacity:string=''
    color:string=''
    model:string=''
    mileage:string=''
    kerbWeight:string=''
    seatHeight:string=''
    transmission:string=''
}